Adding useful echo output for when gradle-assemble is run outside of a Git root.

diff --git a/bin/bin.symlink/gradle-assemble b/bin/bin.symlink/gradle-assemble
--- a/bin/bin.symlink/gradle-assemble
+++ b/bin/bin.symlink/gradle-assemble
@@ -1,6 +1,7 @@
 git status &> /dev/null
-if [ $? -eq 0 ]
-then
+if [ $? -eq 0 ]; then
   BRANCH=`git branch | grep \* | awk '{print $2}'`
-  gradle assemble -i -PbuildNumber=1 -PcommonBranchName=${BRANCH}
+  gradle assemble -i -PbuildNumber=1 -PcommonBranchName=$BRANCH
+else
+  echo "Not in a Git project, can't determine branch."
 fi
